### ISSUE TITLE
bummer this doesn't work anymore, would help with traveling a lot!

### ISSUE THREAD

**Issue by jahamed** [samm81/gmaps-multi-save#1]
Was definitely looking for something similar to this so bummer it doesn't work anymore! My knowledge is pretty basic but if you have ideas on how to fix this/different approaches and just don't have the time to implement it I could take a look at it. Always thought it would be cool to generate a google maps link for different trips from a list of blogs :)

**Comment by samm81** [comment]
wow never expected anyone else to find this haha 😂

the issue is with navigation (as documented in the `readme`). I've been experimenting with making [`goToUrl`](https://github.com/samm81/gmaps-multi-save/blob/72eb8a5a9fef608998eb7ada02d25c3495053934/gmaps-add.js#L17) instead click on the search box, type in the `name` (instead of `url`), and input `enter`, but, as you said, just didn't have the time. welcome to take a stab!
